name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialize Node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: vjdcpapp
          TARGET_BRANCH: main
          TARGET_NAME: test
